# Generated by Django 3.0.3 on 2022-06-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='type',
            field=models.CharField(choices=[('BUYER', 'buyer faqs'), ('SELLER', 'seller faqs'), ('GENERAL', 'general faqs'), ('TRUST', 'trust & safety')], default='buyer', max_length=7),
        ),
    ]
