# Generated by Django 4.0.6 on 2022-08-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applink',
            name='app',
            field=models.CharField(choices=[('VIBER', 'viber'), ('WHATSAPP', 'whatsapp')], max_length=20),
        ),
    ]
