# Generated by Django 4.0.6 on 2022-07-07 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OFFENCE', 'offensive content'), ('DUPLICATE', 'duplicate ad'), ('FRAUD', 'fraud'), ('SOLD', 'product already sold'), ('OTHERS', 'others')], max_length=9)),
                ('msg', models.TextField(blank=True, max_length=500, null=True)),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ads')),
            ],
        ),
    ]
