# Generated by Django 4.0.6 on 2022-08-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ads_adid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='adid',
            new_name='ad_id',
        ),
    ]
