# Generated by Django 4.0.6 on 2022-08-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ads_ad_id_ads_ad_views_alter_ads_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ad_id',
            field=models.CharField(max_length=13),
        ),
    ]
