# Generated by Django 4.0.3 on 2022-08-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_rename_adid_ads_ad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ad_id',
            field=models.CharField(default='AM5449758541', max_length=13),
        ),
    ]
