# Generated by Django 4.0.6 on 2022-08-11 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_remove_ads_category_ads_main_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='sub_categorys',
        ),
        migrations.AddField(
            model_name='ads',
            name='sub_category',
            field=models.CharField(choices=[], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='ads',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_categories', to='ads.category'),
        ),
    ]
