# Generated by Django 4.0.6 on 2022-08-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_ads_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/ads'),
        ),
    ]
