# Generated by Django 3.0.3 on 2022-06-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0002_auto_20220621_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpcenter',
            name='category',
            field=models.CharField(choices=[('BUYER', 'buyer faqs'), ('SELLER', 'seller faqs'), ('GENERAL', 'general faqs'), ('TRUST', 'trust & safety')], db_index=True, default='buyer', max_length=100),
        ),
    ]
