# Generated by Django 4.0.6 on 2022-08-18 06:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_blog_type_blog_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_category',
            options={'ordering': ('-created_at',), 'verbose_name': 'Blog_category', 'verbose_name_plural': 'Blog_categories'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
