# Generated by Django 4.0.6 on 2022-08-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_category_options_alter_blog_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Helpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpful', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=3)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
        ),
    ]
