# Generated by Django 4.0.6 on 2022-08-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_created_by_blog_helpful_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_Helpful',
            new_name='BlogHelpful',
        ),
    ]
