# Generated by Django 3.0.3 on 2022-06-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terms',
            options={'ordering': ('-created_at',), 'verbose_name': 'Term', 'verbose_name_plural': 'Terms'},
        ),
    ]
