# Generated by Django 4.0.6 on 2022-08-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_status',
            field=models.BooleanField(default=True, verbose_name='IS LOGIN'),
        ),
    ]
