# Generated by Django 4.0.3 on 2022-08-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_login_status'),
        ('authentication', '0009_alter_customuser_image'),
    ]

    operations = [
    ]
