# Generated by Django 3.0.3 on 2022-06-29 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='ads',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ads.Ads'),
        ),
    ]
